{{- if .Values.cpuCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vce-validator.name" . }}-cpu-check-job
spec:
  template:
    spec:
      containers:
        - name: stress-test
          image: polinux/stress
          command: ["stress"]
          args: ["--cpu", "2", "--timeout", "30s"]
      restartPolicy: Never
  backoffLimit: 0 # Ensure the Job does not retry if it fails
{{- end }}
