{{- if .Values.diskCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vce-validator.name" . }}-disk-check-job
spec:
  template:
    spec:
      containers:
        - name: disk-check
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - "dd if=/dev/zero of=/tmp/output bs=8k count=1000 && rm /tmp/output"
      restartPolicy: Never
  backoffLimit: 0 # Ensure the Job does not retry if it fails
{{- end }}