{{- if .Values.networkCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include ".Chart.Name" }}-network-check-job
spec:
  template:
    spec:
      containers:
        - name: network-check
          image: curlimages/curl
          args: ["curl", "-s", "https://www.google.com"]
      restartPolicy: Never
  backoffLimit: 0 # Ensure the Job does not retry if it fails
{{- end }}